### ISSUE TITLE
🐛BPMN-Studio Dev-Setup breaks with minstall 3 due to Broken aurelia-cli-dependencies

### ISSUE THREAD

**Issue by heikomat** [process-engine/process_engine_meta#20]
#### Describe your issue

The charon-installation does not work correctly with minstall 3, because the dependency-list of the aurelia-cli-package is broken, see [this issue](https://github.com/aurelia/cli/issues/801). If that is fixed and the aurelia-cli-dependency updated, this should work again

#### How can others reproduce the issue?

run the regular dev-setup with minstall 3. building charon won't work because of a wrong gulp version. you'll get this error:

```
TypeError: Cannot read property 'apply' of undefined
    at Gulp.gulp.(anonymous function) [as series] (/Users/heiko/Desktop/Projekte/BPMN/process_engine_meta/node_modules/aurelia-cli/lib/commands/gulp.js:72:21)
    at process.nextTick (/Users/heiko/Desktop/Projekte/BPMN/process_engine_meta/node_modules/aurelia-cli/lib/commands/gulp.js:30:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

#### Possible solution

The dependency-list in the aurelia-cli needs to be fixed

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): OS X 10.12.6
- Node (`node --version`): 8.9.4
- NPM (`npm --version`): 5.6.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
I opened a PR for this: https://github.com/aurelia/cli/pull/803
